CC = gcc 

TARGET = covid19

CFLAGS = -Wall -std=c11 -O3

all:
		$(CC) $(CFLAGS) -o $(TARGET) covid19.c textoAjuda.c manipulacaoFicheiros.c listas.c input.c ordenacaoDados.c selecaoDados.c restricaoDados.c

clear:
		rm $(TARGET)